---

- name: install mongodb
  homebrew: name={{ item }} state=latest
  with_items:
    - mongodb

- name: check if mongodb is loaded
  shell: brew services list | grep mongodb
  changed_when: False
  register: mongodb_loaded_result

- name: launch mongodb
  shell: brew sevices start mongodb
  when: "'started' not in mongodb_loaded_result.stdout"
